# Generated by Django 4.2.2 on 2023-07-03 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_todoitem_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoitem',
            options={'ordering': ['complete']},
        ),
        migrations.RenameField(
            model_name='todoitem',
            old_name='completed',
            new_name='complete',
        ),
    ]
